name: tsurugidb-CI

on: [push, pull_request, workflow_dispatch]

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
    runs-on: [self-hosted, docker]
    timeout-minutes: 30
    container:
      image: ghcr.io/project-tsurugi/oltp-sandbox:${{ matrix.os }}
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}
      volumes:
        - ${{ vars.ccache_dir }}:${{ vars.ccache_dir }}
        - ${{ vars.gradle_cache_dir }}:/root/.gradle
    defaults:
      run:
        shell: bash
    env:
      CCACHE_CONFIGPATH: ${{ vars.ccache_dir }}/ccache.conf
      CCACHE_DIR: ${{ vars.ccache_dir }}/${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GHA_PAT }}

      - name: Install
        run: |
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"

          mkdir build-install-test
          ./install.sh --prefix="$(pwd)/build-install-test"
        env:
          TG_COMMON_CMAKE_BUILD_OPTIONS: '-DCMAKE_CXX_COMPILER_LAUNCHER=ccache'

      - name: Generate_Install_Archive
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        run: |
          ./dist/install/generate-install-archive.sh

      - name: Upload_Artifact
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        uses: actions/upload-artifact@v3
        with:
          name: install-archive
          path: tsurugidb-*.tar.gz
          retention-days: 30

  Test:
    uses: ./.github/workflows/ci-test-modules.yml
    secrets: inherit
    permissions:
      checks: write
